### ISSUE TITLE
cuda-version

### ISSUE THREAD

**Issue by zhizunhu** [rpng/calc2.0#2]
Hi!:
    I'd like to know which cuda your great programer is testing on.

**Comment by nmerrill67** [comment]
The training code was tested on CUDA 10.0. Testing has been run on CPU and CUDA 9.2 as well. Are you having CUDA issues? Sorry for the delay I did not see this issue.

**Comment by zhizunhu** [comment]
Thanks for your answer，I have finished training and testing on the Campus Dataset. But I have a question that: in the get_prec_recall part, you are choosing top 7 of sims to calculate pairs Fundamentalmat, right? But I find some true positive pairs are changed to true negative. Does it have influence to the final result?

**Comment by zhizunhu** [comment]
OK, thanks for your help and waiting for your paper.
